---
- name: Install nginx with Virtual hosts
  hosts: webservers
  remote_user: nuck_figgers
  become: true
  become_method: sudo
  gather_facts: no

  vars:
    sites:
    - "etis.com"
    - "fizfak.com"
    - "mehmat.ru"

  roles:
  - nginx-vhosts
